name: flutter_markdown_example
description: Demonstrates how to use the flutter_markdown package.
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_markdown:
    path: ../

flutter:
  uses-material-design: true
