name: flutter_markdown
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A Markdown renderer for Flutter.
homepage: https://github.com/flutter/flutter_markdown
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter
  markdown: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

flutter:
  assets:
    - assets/logo.png
